import { translate } from "../utils/i18n.js";

const UI = {
  loading: ["正在讀取寵物小屋資料⋯", "Loading Pet Home…", "ペットのおうちを読み込み中…", "펫 하우스를 불러오는 중…"],
  back: ["返回", "Back", "戻る", "뒤로"], houseSettings: ["小屋設定", "Pet Home Settings", "おうちの設定", "펫 하우스 설정"], petHome: ["寵物小屋", "Pet Home", "ペットのおうち", "펫 하우스"], managePreferences: ["管理寵物與遊戲偏好", "Manage your pet and play preferences", "ペットと遊び方の設定", "반려동물과 플레이 설정 관리"], liveWith: ["和{name}一起生活", "Living with {name}", "{name}との暮らし", "{name}와 함께하는 생활"], petSettings: ["寵物小屋設定", "Pet Home settings", "ペットのおうちの設定", "펫 하우스 설정"],
  moodHappy: ["開心", "Happy", "ごきげん", "행복함"], moodCalm: ["平靜", "Calm", "穏やか", "평온함"], moodNeedCare: ["需要照顧", "Needs care", "お世話が必要", "돌봄 필요"], hunger: ["飽食", "Fullness", "満腹", "포만감"], mood: ["心情", "Mood", "気分", "기분"], clean: ["清潔", "Cleanliness", "清潔", "청결"], energy: ["精神", "Energy", "元気", "기력"],
  bondFamiliar: ["還在熟悉", "Getting acquainted", "まだ慣れている途中", "아직 알아가는 중"], bondLikeYou: ["喜歡你", "Fond of you", "好き", "좋아해요"], bondFriends: ["好朋友", "Good friends", "仲良し", "좋은 친구"], bondInseparable: ["形影不離", "Inseparable", "いつも一緒", "늘 함께"],
  initialGreeting: ["今天也要一起開心喔！", "Let's have another happy day together!", "今日も一緒に楽しく過ごそう！", "오늘도 함께 즐겁게 보내자!"], dragPlaced: ["放在這裡嗎？好呀～", "Here? Sounds good!", "ここにする？いいよ～", "여기에 둘까? 좋아~"], levelUp: ["我升到 Lv.{level} 了！獲得 {coins} 星星幣✨", "I reached Lv.{level}! We earned {coins} Star Coins ✨", "Lv.{level}になった！スターコインを{coins}枚もらったよ✨", "Lv.{level}이 됐어! 별 코인 {coins}개를 받았어✨"],
  fullFeed: ["肚子已經飽飽的～", "My tummy is already full!", "もうおなかいっぱいだよ～", "배가 이미 든든해~"], fullPlay: ["今天已經玩得超開心了！", "I have already had so much fun today!", "今日はもうたくさん遊んで大満足！", "오늘은 이미 신나게 놀았어!"], fullClean: ["我已經乾乾淨淨啦～", "I am already squeaky clean!", "もうぴかぴかだよ～", "이미 깨끗해~"], fullSleep: ["精神滿滿，還不想睡～", "I am full of energy and not sleepy yet!", "元気いっぱいで、まだ眠くないよ～", "기운이 넘쳐서 아직 자고 싶지 않아~"], renameGreeting: ["以後請叫我「{name}」！", "Please call me “{name}” from now on!", "これからは「{name}」って呼んでね！", "이제부터 나를 “{name}”라고 불러 줘!"], untitledEntry: ["我的記事", "My Entry", "わたしの記録", "내 기록"],
  home: ["小屋", "Home", "おうち", "집"], park: ["公園", "Park", "公園", "공원"], beach: ["海邊", "Beach", "海辺", "해변"], longPressDrag: ["長按拖曳{name}", "Long press to drag {name}", "長押しして{name}を動かす", "길게 눌러 {name} 드래그"],
  feed: ["餵食", "Feed", "ごはん", "먹이 주기"], play: ["玩耍", "Play", "遊ぶ", "놀기"], cleanAction: ["洗澡", "Bathe", "お風呂", "목욕"], sleep: ["休息", "Rest", "休む", "쉬기"],
  decorateSoon: ["小屋布置準備中", "Decorating is coming soon", "おうちの模様替えは準備中", "집 꾸미기는 준비 중이에요"], decorateSoonDescription: ["我們正在準備與寵物風格一致的新家具，之後再一起打造溫暖的小屋吧！", "New furniture that fits your pet is on the way. Let's make a warm home together soon!", "ペットに似合う新しい家具を準備中です。一緒にあたたかなおうちを作りましょう！", "반려동물에게 어울리는 새 가구를 준비하고 있어요. 곧 함께 따뜻한 집을 만들어요!"],
  diaryTitle: ["{name}日記", "{name}'s Diary", "{name}の日記", "{name}의 일기"], diarySubtitle: ["牠會自己記下你們的小日常", "Your pet keeps little memories of your days together", "ふたりの小さな日常を、ペットが書き留めます", "함께한 작은 일상을 반려동물이 기록해요"], collapse: ["收起", "Collapse", "閉じる", "접기"], writeDiary: ["寫日記", "Write diary", "日記を書く", "일기 쓰기"], optionalTitle: ["標題（可留空）", "Title (optional)", "タイトル（任意）", "제목 (선택)"], dailyNote: ["記下今天和{name}的小事…", "Write a little moment from today with {name}…", "今日{name}と過ごした小さな出来事を記録…", "오늘 {name}와 함께한 작은 일을 기록해 보세요…"], cancel: ["取消", "Cancel", "キャンセル", "취소"], saveToDiary: ["存進日記", "Save to diary", "日記に保存", "일기에 저장"], save: ["儲存", "Save", "保存", "저장"], handwritten: ["手寫", "Written by you", "手書き", "직접 작성"], editNote: ["編輯註記", "Edit note", "メモを編集", "메모 수정"], addNote: ["補寫幾句", "Add a note", "ひとこと添える", "메모 남기기"], confirmDelete: ["確定刪除這篇記事？", "Delete this entry?", "この記録を削除しますか？", "이 기록을 삭제할까요?"], delete: ["刪除", "Delete", "削除", "삭제"], edit: ["編輯", "Edit", "編集", "수정"], editOrDelete: ["編輯或刪除這篇記事", "Edit or delete this entry", "この記録を編集または削除", "이 기록 수정 또는 삭제"], notePlaceholder: ["幫這段回憶補寫幾句…", "Add a few words to this memory…", "この思い出にひとこと添える…", "이 추억에 몇 마디를 남겨 보세요…"], lockedMemories: ["繼續互動、升級與到處冒險，會解鎖更多回憶（{count} / {total}）", "Keep caring, growing, and exploring to unlock more memories ({count} / {total})", "お世話や成長、冒険を続けると、もっと思い出が解放されます（{count} / {total}）", "돌보고 성장하고 모험하며 더 많은 추억을 잠금 해제하세요 ({count} / {total})"],
  myPets: ["我的寵物", "My Pet", "わたしのペット", "내 반려동물"], petsSubtitle: ["查看資料、成長紀錄與切換夥伴", "View details, growth, and companions", "プロフィールや成長記録、仲間を確認", "정보, 성장 기록, 동반자를 확인하세요"], onePet: ["1 隻", "1 pet", "1匹", "1마리"], currentCompanion: ["目前的夥伴", "Current companion", "今のパートナー", "현재의 동반자"], togetherDays: ["相伴 {days} 天", "Together for {days} days", "出会って {days} 日", "함께한 지 {days}일"], bond: ["親密度", "Bond", "親密度", "친밀도"], growthLevel: ["成長等級", "Growth level", "成長レベル", "성장 레벨"], unlockedMemories: ["解鎖回憶", "Unlocked memories", "解放した思い出", "해제된 추억"], todayBond: ["今日親密度 {value} / {total}", "Today's bond {value} / {total}", "今日の親密度 {value} / {total}", "오늘의 친밀도 {value} / {total}"], basicInfo: ["基本資料", "Basic info", "基本情報", "기본 정보"], basicInfoSub: ["名字、生日、品種與個性", "Name, birthday, species, and personality", "名前、誕生日、種類、性格", "이름, 생일, 종, 성격"], growthRecord: ["成長紀錄", "Growth record", "成長記録", "성장 기록"], growthRecordSub: ["查看相遇以來的里程碑", "See milestones since you met", "出会ってからの節目を見る", "만난 뒤의 이정표를 확인하세요"], welcomePet: ["迎接新寵物", "Welcome a new pet", "新しいペットを迎える", "새 반려동물 맞이하기"], welcomePetSub: ["未來可在這裡新增或切換寵物", "You will be able to add or switch pets here", "ここでペットの追加や切り替えができるようになります", "여기에서 반려동물을 추가하거나 바꿀 수 있게 될 거예요"], growthSubtitle: ["和{name}相遇以來的里程碑", "Milestones since meeting {name}", "{name}と出会ってからの節目", "{name}와 만난 뒤의 이정표"], remainingMilestones: ["還有 {count} 個里程碑，等你們一起去發現", "{count} milestones are waiting to be discovered together", "あと {count} 個の節目を、一緒に見つけよう", "함께 발견할 이정표가 {count}개 남아 있어요"], quietDays: ["也有一些安靜的日子，牠都記著", "There were quiet days too. Your pet remembers them.", "静かな日々も、ペットは覚えています", "조용한 날들도 반려동물은 기억하고 있어요"], createPersonality: ["建立專屬於牠的個性", "Shape a personality just for your pet", "この子だけの性格を作ろう", "반려동물만의 성격을 만들어 보세요"], name: ["名字", "Name", "名前", "이름"], birthday: ["生日", "Birthday", "誕生日", "생일"], species: ["品種", "Species", "種類", "종"], gender: ["性別", "Gender", "性別", "성별"], primaryPersonality: ["主要個性", "Primary personality", "主な性格", "주요 성격"], secondaryPersonality: ["次要個性", "Secondary personality", "第二の性格", "보조 성격"], likes: ["喜歡的事", "Likes", "好きなこと", "좋아하는 것"], dislikes: ["討厭的事", "Dislikes", "苦手なこと", "싫어하는 것"], enterPetName: ["輸入寵物名字", "Enter a pet name", "ペットの名前を入力", "반려동물 이름 입력"], exampleSecondary: ["例如：貪吃、好奇", "For example: foodie, curious", "例：食いしんぼう、好奇心旺盛", "예: 먹보, 호기심 많음"], exampleLikes: ["例如：摸摸、肉肉、公園", "For example: pets, treats, parks", "例：なでなで、おやつ、公園", "예: 쓰다듬기, 간식, 공원"], exampleDislikes: ["例如：打雷、洗澡太久", "For example: thunder, long baths", "例：雷、長いお風呂", "예: 천둥, 긴 목욕"], saveProfile: ["儲存資料", "Save profile", "プロフィールを保存", "프로필 저장"],
  mapAndActivity: ["地圖與活動", "Maps & activity", "マップとアクティビティ", "지도와 활동"], chooseMap: ["選擇地圖", "Choose map", "マップを選ぶ", "지도 선택"], chooseMapSub: ["小屋、公園與海邊", "Home, park, and beach", "おうち、公園、海辺", "집, 공원, 해변"], freeRoam: ["自由活動", "Free roaming", "自由に歩く", "자유 활동"], freeRoamSub: ["寵物會自行在場景中走動", "Your pet wanders around the scene", "ペットが場面を自由に歩きます", "반려동물이 장면 안을 자유롭게 돌아다녀요"], desktopPet: ["桌面小寵物", "Desktop pet", "デスクトップペット", "데스크톱 펫"], desktopPetSub: ["有機會出現在桌面或其他 App", "May appear on the home screen or in other apps", "ホーム画面や他のアプリに現れることがあります", "홈 화면이나 다른 앱에 나타날 수 있어요"], returnTime: ["回小屋休息時間", "Return-home rest time", "おうちに戻る休憩時間", "집으로 돌아가는 휴식 시간"], returnTimeSub: ["拖進小屋後暫時不再出現", "After being returned home, your pet stays there for a while", "おうちに戻すと、しばらく現れません", "집으로 옮기면 잠시 나타나지 않아요"], minutes: ["{value} 分鐘", "{value} min", "{value} 分", "{value}분"], aiDiary: ["AI 日記", "AI diary", "AI日記", "AI 일기"], personalizedDiary: ["AI 個人化日記", "Personalized AI diary", "AIパーソナル日記", "AI 맞춤 일기"], aiConfigured: ["由 AI 依個性撰寫回憶、日常與回應", "AI writes memories, daily entries, and replies based on personality", "AIが性格に合わせて思い出、日常、返信を書きます", "AI가 성격에 맞춰 추억, 일상, 답글을 작성해요"], aiNotConfigured: ["尚未設定 AI 連線，將使用內建文案", "AI is not configured; built-in writing will be used", "AI接続が未設定のため、内蔵文を使用します", "AI 연결이 설정되지 않아 기본 문구를 사용해요"], reminders: ["提醒", "Reminders", "通知", "알림"], careReminder: ["照顧提醒", "Care reminders", "お世話リマインダー", "돌봄 알림"], careReminderSub: ["寵物需要照顧時通知", "Notify when your pet needs care", "お世話が必要なときに通知", "돌봄이 필요할 때 알림"], dataManagement: ["資料管理", "Data management", "データ管理", "데이터 관리"], exportPetData: ["匯出寵物資料", "Export pet data", "ペットデータを書き出す", "반려동물 데이터 내보내기"], exportPetDataSub: ["下載寵物小屋專用 JSON 備份", "Download a Pet Home JSON backup", "ペットのおうち専用JSONバックアップをダウンロード", "펫 하우스 전용 JSON 백업 다운로드"], importPetData: ["匯入寵物資料", "Import pet data", "ペットデータを読み込む", "반려동물 데이터 가져오기"], importPetDataSub: ["從先前的備份檔恢復進度", "Restore progress from an earlier backup", "以前のバックアップから進行状況を復元", "이전 백업에서 진행 상황 복원"], download: ["下載", "Download", "ダウンロード", "다운로드"], chooseFile: ["選擇檔案", "Choose file", "ファイルを選ぶ", "파일 선택"], exportSuccess: ["寵物資料已匯出", "Pet data exported", "ペットデータを書き出しました", "반려동물 데이터를 내보냈어요"], exportDocuments: ["寵物資料已匯出到 Documents/{path}", "Pet data exported to Documents/{path}", "ペットデータをDocuments/{path}へ書き出しました", "반려동물 데이터를 Documents/{path}에 내보냈어요"], exportFail: ["匯出失敗：{message}", "Export failed: {message}", "書き出しに失敗しました：{message}", "내보내기에 실패했어요: {message}"], importSuccess: ["匯入成功，寵物資料已恢復", "Import complete. Pet data restored.", "読み込み完了。ペットデータを復元しました。", "가져오기 완료. 반려동물 데이터를 복원했어요."], importFail: ["匯入失敗：不是有效的寵物小屋備份檔", "Import failed: this is not a valid Pet Home backup.", "読み込みに失敗しました。有効なペットのおうちバックアップではありません。", "가져오기에 실패했어요. 유효한 펫 하우스 백업이 아니에요."], prototype: ["寵物小屋 · Prototype 0.2", "Pet Home · Prototype 0.2", "ペットのおうち · Prototype 0.2", "펫 하우스 · Prototype 0.2"], decorate: ["布置", "Decorate", "模様替え", "꾸미기"], diary: ["日記", "Diary", "日記", "일기"], pets: ["寵物", "Pets", "ペット", "반려동물"],
  personality_clingy: ["黏人", "Clingy", "甘えんぼ", "애교 많은"], personality_lively: ["活潑", "Lively", "元気", "활발한"], personality_foodie: ["貪吃", "Foodie", "食いしんぼう", "먹보"], personality_lazy: ["慵懶", "Laid-back", "のんびり", "느긋한"], personality_shy: ["害羞", "Shy", "恥ずかしがり", "수줍은"], personality_gentle: ["溫柔", "Gentle", "やさしい", "다정한"], personality_mischievous: ["調皮", "Mischievous", "いたずらっ子", "장난꾸러기"], gender_unspecified: ["未設定", "Unspecified", "未設定", "미설정"], gender_male: ["男生", "Male", "男の子", "수컷"], gender_female: ["女生", "Female", "女の子", "암컷"],
};

export function petUiText(locale, key, values = {}) {
  const entry = UI[key];
  const value = entry ? translate(locale, ...entry) : key;
  return Object.entries(values).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, String(replacement)), value);
}
