import { useCallback, useEffect, useRef, useState } from "react";
import { createDefaultVoiceSettings } from "../../utils/voiceSettings";

export default function useVoicePlayback({ config, setConfig, fetchVoices, synthesizeSpeech, getSpeechText, showToast, sanitizeText, tr }) {
  const [voices, setVoices] = useState([]);
  const [connectionState, setConnectionState] = useState("idle");
  const [playback, setPlayback] = useState({ key: null, status: "idle" });
  const audioRef = useRef(null);
  const cacheRef = useRef(new Map());

  const stop = useCallback(() => { const current = audioRef.current; if (!current) return; current.audio.pause(); URL.revokeObjectURL(current.url); audioRef.current = null; }, []);
  const playBlob = useCallback(async (blob, key) => {
    stop(); const url = URL.createObjectURL(blob); const audio = new Audio(url); audioRef.current = { audio, url, key };
    const reset = () => { if (audioRef.current?.audio === audio) audioRef.current = null; URL.revokeObjectURL(url); setPlayback({ key: null, status: "idle" }); };
    audio.onended = reset; audio.onerror = () => { reset(); showToast(tr("語音播放失敗", "Voice playback failed", "音声の再生に失敗しました", "음성 재생 실패")); };
    await audio.play(); setPlayback({ key, status: "playing" });
  }, [stop, showToast, tr]);
  const previewCharacterVoice = useCallback(async (voiceSettings, text) => { try { await playBlob(await synthesizeSpeech({ text, config, voiceSettings }), "voice-preview"); } catch (error) { showToast(`${tr("語音試聽失敗", "Voice preview failed", "音声試聴に失敗しました", "음성 미리듣기 실패")}：${sanitizeText(error?.message || "", 120)}`); } }, [config, playBlob, synthesizeSpeech, showToast, tr, sanitizeText]);
  const loadDefaultVoices = useCallback(async () => { try { setConnectionState("loading"); const list = await fetchVoices(config.elevenlabs?.apiKey || ""); if (!list.length) throw new Error(tr("找不到可用聲音", "No available voices found", "利用可能な音声が見つかりません", "사용 가능한 음성을 찾을 수 없습니다")); setVoices(list); setConfig((current) => ({ ...current, elevenlabs: { ...current.elevenlabs, availableVoices: list, defaultVoiceId: list.some((voice) => voice.id === current.elevenlabs?.defaultVoiceId) ? current.elevenlabs.defaultVoiceId : list[0].id } })); setConnectionState("success"); showToast(tr(`連線成功，已載入 ${list.length} 個可用聲音`, `Connected; loaded ${list.length} available voices`, `接続成功：${list.length}件の音声を読み込みました`, `연결 성공: 사용 가능한 음성 ${list.length}개를 불러왔습니다`)); } catch (error) { setVoices([]); setConnectionState("error"); showToast(`${tr("ElevenLabs 連線失敗", "ElevenLabs connection failed", "ElevenLabs 接続失敗", "ElevenLabs 연결 실패")}：${sanitizeText(error?.message || "", 120)}`); } }, [config, fetchVoices, setConfig, showToast, tr, sanitizeText]);
  const previewDefaultVoice = useCallback(async () => { const provider = config.provider || "elevenlabs"; try { setConnectionState("previewing"); const settings = createDefaultVoiceSettings(); settings.enabled = true; settings[provider].voiceId = config[provider]?.defaultVoiceId || ""; await playBlob(await synthesizeSpeech({ text: tr("你好，語音 API 已連線成功。", "Hello, the voice API is connected.", "こんにちは、音声 API の接続に成功しました。", "안녕하세요, 음성 API 연결에 성공했습니다."), config, voiceSettings: settings }), "tts-default-preview"); setConnectionState("success"); } catch (error) { setConnectionState("error"); showToast(`${tr("語音測試失敗", "Voice test failed", "音声テストに失敗しました", "음성 테스트 실패")}：${sanitizeText(error?.message || "", 120)}`); } }, [config, playBlob, synthesizeSpeech, showToast, tr, sanitizeText]);
  const toggleCharacterVoice = useCallback(async (character, message) => { const settings = character?.voiceSettings; if (!config.enabled || !settings?.enabled) return; const provider = config.provider || "elevenlabs"; const voiceId = settings?.[provider]?.voiceId?.trim(); if (!config?.[provider]?.apiKey) return showToast(tr("請先到設定填寫語音 API Key", "Set the voice API key in Settings first", "設定で音声 API Key を入力してください", "설정에서 음성 API Key를 입력해주세요")); if (!voiceId) return showToast(tr("請先在角色設定填寫 Voice ID", "Set a Voice ID in character settings first", "キャラ設定で Voice ID を入力してください", "캐릭터 설정에서 Voice ID를 입력해주세요")); const key = `${provider}:${character.id}:${message.replyGroupId || message.id}`; if (playback.key === key && playback.status === "playing" && audioRef.current?.audio) { audioRef.current.audio.pause(); setPlayback({ key, status: "paused" }); return; } if (playback.key === key && playback.status === "paused" && audioRef.current?.audio) { await audioRef.current.audio.play(); setPlayback({ key, status: "playing" }); return; } const text = getSpeechText(character.id, message); if (!text) return showToast(tr("這段回覆沒有可朗讀的角色台詞", "This reply has no character dialogue to read", "この返信には読み上げる台詞がありません", "이 답변에는 읽을 캐릭터 대사가 없습니다")); const cacheKey = `${key}:${config[provider]?.model || ""}:${voiceId}:${text}`; try { setPlayback({ key, status: "loading" }); let blob = cacheRef.current.get(cacheKey); if (!blob) { blob = await synthesizeSpeech({ text, config, voiceSettings: settings }); cacheRef.current.set(cacheKey, blob); } await playBlob(blob, key); } catch (error) { setPlayback({ key: null, status: "idle" }); showToast(`${tr("語音生成失敗", "Voice generation failed", "音声生成に失敗しました", "음성 생성 실패")}：${sanitizeText(error?.message || "", 120)}`); } }, [config, playback, getSpeechText, showToast, tr, synthesizeSpeech, playBlob, sanitizeText]);
  const clearCache = useCallback(() => { stop(); cacheRef.current.clear(); setPlayback({ key: null, status: "idle" }); }, [stop]);
  useEffect(() => () => stop(), [stop]);
  return { voices, setVoices, connectionState, setConnectionState, playback, stop, clearCache, previewCharacterVoice, loadDefaultVoices, previewDefaultVoice, toggleCharacterVoice };
}
