import React, { useState } from "react";

export default function WalletLedgerView({ wallet, setWallet, characters, closeApp, openSettings, tr, formatMoney, displayWalletText, sanitizeUserImageUrl }) {
  const [tab, setTab] = useState("ledger");
  const [filter, setFilter] = useState(null);
  const [monthOffset, setMonthOffset] = useState(0);
  const [visible, setVisible] = useState(80);
  const txCharId = (tx) => {
    if (tx?.charId) return tx.charId;
    const note = String(tx?.note || "");
    return [...characters].sort((a,b)=>(b.name||"").length-(a.name||"").length).find((c) => c.name && note.includes(c.name))?.id || null;
  };
  const txs = [...(wallet?.transactions || [])].filter((t) => !filter || txCharId(t) === filter).sort((a,b)=>(b.time||0)-(a.time||0));
  const dayKey = (time) => { const d=new Date(time); return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`; };
  const groups = txs.slice(0, visible).reduce((out,t) => { const key=dayKey(t.time); let g=out[out.length-1]; if(!g||g.key!==key){const d=new Date(t.time),now=new Date(); const label=key===dayKey(Date.now())?tr("今天","Today","今日","오늘"):key===dayKey(Date.now()-864e5)?tr("昨天","Yesterday","昨日","어제"):`${d.getMonth()+1}/${d.getDate()}`; g={key,label,items:[]};out.push(g);} g.items.push(t);return out; },[]);
  const now=new Date(), mDate=new Date(now.getFullYear(),now.getMonth()+monthOffset,1);
  const monthTx=txs.filter((t)=>{const d=new Date(t.time);return d.getFullYear()===mDate.getFullYear()&&d.getMonth()===mDate.getMonth()&&t.source!=="manual";});
  const income=monthTx.filter(t=>t.type!=="expense").reduce((s,t)=>s+(Number(t.amount)||0),0), expense=monthTx.filter(t=>t.type==="expense").reduce((s,t)=>s+(Number(t.amount)||0),0);
  const weeks=[0,0,0,0,0]; monthTx.forEach(t=>weeks[Math.min(4,Math.floor((new Date(t.time).getDate()-1)/7))]+=Number(t.amount)||0); const maxWeek=Math.max(1,...weeks);
  const setBalance=()=>{const raw=prompt(tr("設定玩家錢包餘額","Set wallet balance","残高を設定","잔액 설정"),String(wallet?.balance||0));if(raw===null)return;const next=Math.max(0,Math.round(Number(raw)||0)),diff=next-(wallet?.balance||0);setWallet(w=>({...w,balance:next,transactions:diff?[{id:gid(),type:diff<0?"expense":"income",amount:Math.abs(diff),note:tr("調整餘額","Balance adjusted","残高調整","잔액 조정"),time:Date.now(),source:"manual"},...(w?.transactions||[])].slice(0,1000):(w?.transactions||[])}));};
  const toggleMemorial=(tx)=>{const label=tx.memorial?null:prompt(tr("珍藏標籤","Saved label","保存ラベル","소장 라벨"),tr("珍藏","Saved","保存","소장"));if(label===null&&!tx.memorial)return;setWallet(w=>({...w,transactions:(w.transactions||[]).map(x=>x.id===tx.id?(tx.memorial?(({memorial,...rest})=>rest)(x):{...x,memorial:{label:label||tr("珍藏","Saved","保存","소장")}}):x)}));};
  const biggest=monthTx.reduce((m,t)=>!m||Number(t.amount)>Number(m.amount)?t:m,null);
  const weekOut=[0,0,0,0,0], weekIn=[0,0,0,0,0]; monthTx.forEach(t=>{const i=Math.min(4,Math.floor((new Date(t.time).getDate()-1)/7));(t.type==="expense"?weekOut:weekIn)[i]+=Number(t.amount)||0;});
  const monthMaxWeek=Math.max(1,...weekOut,...weekIn), memorials=monthTx.filter(t=>t.memorial), biggestWeek=biggest?Math.min(5,Math.floor((new Date(biggest.time).getDate()-1)/7)+1):0;
  const selectedName=filter?(characters.find(c=>c.id===filter)?.name||tr("角色","Character","キャラ","캐릭터")):tr("角色們","Characters","キャラたち","캐릭터들");
  const keywordTx=monthTx.find(t=>["生日","紅包","紀念","第一次"].some(k=>String(t.note||"").includes(k)));
  if(tab==="month") return <div className="mp-page mp-wallet-month"><div className="mp-hdr"><div className="mp-back" onClick={()=>setTab("ledger")}>←</div><div><div className="mp-htitle">{tr("月結","Monthly","月まとめ","월결산")}</div><div className="mp-wallet-month-sub">{tr("這個月的我們","This month together","今月のふたり","이번 달의 우리")}</div></div></div><div className="mp-cm mp-wallet-month-body">
    <div className="mp-wfilter"><button className={`mp-wchip ${!filter?"active":""}`} onClick={()=>setFilter(null)}>{tr("全部","All","すべて","전체")}</button>{characters.map(c=><button key={c.id} className={`mp-wchip ${filter===c.id?"active":""}`} onClick={()=>setFilter(c.id)}>{c.name}</button>)}</div>
    <div className="mp-wmonth-nav"><button onClick={()=>setMonthOffset(v=>v-1)}>‹</button><span>{mDate.getFullYear()} · {mDate.getMonth()+1}{tr("月","","月","월")}</span><button disabled={monthOffset>=0} onClick={()=>setMonthOffset(v=>v+1)}>›</button></div>
    <div className="mp-wcard mp-month-compare"><div className="mp-wcomp-row"><span>{tr("我 → ","Me → ","わたし → ","나 → ")}{selectedName}</span><b className="mp-month-out">${formatMoney(expense)}</b></div><div className="mp-wbar"><i style={{width:`${expense+income?expense/(expense+income)*100:0}%`}}/></div><div className="mp-wcomp-row"><span>{selectedName}{tr(" → 我"," → me"," → わたし"," → 나")}</span><b className="mp-month-in">${formatMoney(income)}</b></div><div className="mp-wbar gold"><i style={{width:`${expense+income?income/(expense+income)*100:0}%`}}/></div><div className="mp-wcomp-note">{monthTx.length?tr(`來往 ${monthTx.length} 筆，都記在心上 ♡`,`${monthTx.length} exchanges, kept close ♡`,`${monthTx.length} 回のやり取り、心に ♡`,`${monthTx.length}번의 왕래, 마음에 ♡`):tr("這個月還沒有往來","Nothing this month","今月はまだ","이번 달은 아직")}</div></div>
    <div className="mp-wcard"><div className="mp-month-card-title">{tr("每週往來","Weekly exchanges","毎週のやり取り","주별 왕래")}</div><div className="mp-wweeks mp-wweeks-dual">{weekOut.map((out,i)=><div className="mp-wweek" key={i}><div className="mp-week-bars"><i className="out" style={{height:`${out/monthMaxWeek*100}%`}}/><i className="in" style={{height:`${weekIn[i]/monthMaxWeek*100}%`}}/></div><small>W{i+1}</small></div>)}</div><div className="mp-week-legend"><span>● {tr("送出","Sent","送った","보냄")}</span><span>● {tr("收到","Received","もらった","받음")}</span></div></div>
    <div className="mp-wnote">{monthTx.length?<>{mDate.getMonth()+1}{tr("月小記：","月 note: ","月メモ：","월 메모: ")}{tr(`互相留下了 ${monthTx.length} 次往來。`,`There were ${monthTx.length} exchanges.`,`やり取りは ${monthTx.length} 回。`,`서로 ${monthTx.length}번 오갔어요.`)}<br/>{memorials.length?tr(`珍藏了 ${memorials.length} 個瞬間。`,`Saved ${memorials.length} moments.`,`${memorials.length} 個の瞬間を保存。`,`${memorials.length}개의 순간을 소장했어요.`):null}{keywordTx?<><br/>{displayWalletText(keywordTx.note)}</>:null}{biggest?<><br/>{tr(`最大一筆是 W${biggestWeek} 的 $${formatMoney(biggest.amount)}。`,`The biggest was $${formatMoney(biggest.amount)} in W${biggestWeek}.`,`最大は W${biggestWeek} の $${formatMoney(biggest.amount)}。`,`가장 큰 금액은 W${biggestWeek}의 $${formatMoney(biggest.amount)}예요.`)}</>:null}</>:tr("這個月還沒有金錢往來。","No transactions this month.","今月はまだやり取りがありません。","이번 달은 아직 거래가 없어요.")}</div>
    {memorials.length>0&&<div className="mp-wmem-shelf"><span>{tr("本月珍藏","Saved this month","今月の保存","이달의 소장")}</span>{memorials.map(t=><button key={t.id} className="mp-wmem-chip" onClick={()=>toggleMemorial(t)}>✦ {t.memorial.label}</button>)}</div>}
  </div></div>;
  return <div className="mp-page"><div className="mp-hdr"><div className="mp-back" onClick={closeApp}>←</div><div><div className="mp-htitle">{tr("錢包","Wallet","ウォレット","지갑")}</div><div style={{font:"10px var(--mp-hand,var(--mp-font))",color:"var(--mp-txt-l)"}}>{tr("我們的小帳本","Our little ledger","ふたりの家計簿","우리의 가계부")}</div></div><button className="mp-ibtn" style={{marginLeft:"auto"}} onClick={openSettings}>⚙</button></div>
  <div className="mp-cm"><div className="mp-bank"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className="mp-bank-label">{tr("我的小金庫","My little vault","わたしの金庫","나의 금고")}</span><button className="mp-bank-edit" onClick={setBalance}>✎ {tr("設定餘額","Set balance","残高設定","잔액 설정")}</button></div><div className="mp-bank-amt">${formatMoney(wallet?.balance||0)}</div><div className="mp-bank-sum" onClick={()=>setTab("month")}>{mDate.getMonth()+1}{tr("月","","月","월")}・{tr("送出","Sent","送った","보냄")} ${formatMoney(expense)} ↔ {tr("收到","Received","もらった","받음")} ${formatMoney(income)}</div></div>
  <div className="mp-wtabs" style={{margin:"11px 0 8px"}}><button className={`mp-wtab ${tab==="ledger"?"active":""}`} onClick={()=>setTab("ledger")}>{tr("流水帳","Ledger","履歴","내역")}</button><button className={`mp-wtab ${tab==="month"?"active":""}`} onClick={()=>setTab("month")}>{tr("月結","Monthly","月まとめ","월결산")}</button></div>
  <div className="mp-wfilter" style={{marginBottom:10}}><button className={`mp-wchip ${!filter?"active":""}`} onClick={()=>setFilter(null)}>{tr("全部","All","すべて","전체")}</button>{characters.map(c=><button key={c.id} className={`mp-wchip ${filter===c.id?"active":""}`} onClick={()=>{setFilter(c.id);setVisible(80);}}>{c.name}</button>)}</div>
  {tab==="ledger"?(txs.length? <>{groups.map(g=><div key={g.key}><div className="mp-wday">{g.label}</div>{g.items.map(t=>{const c=characters.find(x=>x.id===t.charId);return <div key={t.id} className={`mp-wrow ${t.memorial?"memorial":""}`}>{t.memorial&&<span className="mp-wmem-tag">✦ {t.memorial.label}</span>}<div className="mp-wrow-av">{c&&sanitizeUserImageUrl(c.avatar)?<img src={sanitizeUserImageUrl(c.avatar)} alt=""/>:"💼"}</div><div style={{flex:1,minWidth:0}}><div className="mp-wrow-note">{displayWalletText(t.note)}</div><div className="mp-wrow-meta">{new Date(t.time).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}{t.source==="chat"?` · ${tr("來自聊天室","from chat","チャットから","채팅에서")}`:""}</div></div><span className={`mp-wamt ${t.type==="expense"?"out":"in"}`}>{t.type==="expense"?"-":"+"}{formatMoney(t.amount)}</span><button className="mp-wmem-btn" onClick={()=>toggleMemorial(t)}>{t.memorial?"🔖":"♡"}</button></div>})}</div>)}{visible<txs.length&&<button className="mp-save" onClick={()=>setVisible(v=>v+80)}>{tr("載入更多","Load more","もっと見る","더 보기")}</button>}</>:<div className="mp-empty"><div className="mp-empty-i">🧾</div><div className="mp-empty-t">{tr("還沒有往來紀錄","No transactions yet","まだ記録がありません","아직 기록이 없어요")}</div></div>):<div style={{display:"grid",gap:11}}><div className="mp-wmonth-nav"><button onClick={()=>setMonthOffset(v=>v-1)}>‹</button><span>{mDate.getFullYear()} · {mDate.getMonth()+1}{tr("月","","月","월")}</span><button disabled={monthOffset>=0} onClick={()=>setMonthOffset(v=>v+1)}>›</button></div><div className="mp-wcard"><div className="mp-wcomp-row"><span>{tr("送出","Sent","送った","보냄")}</span><b>${formatMoney(expense)}</b></div><div className="mp-wbar"><i style={{width:`${expense+income?expense/(expense+income)*100:0}%`}}/></div><div className="mp-wcomp-row"><span>{tr("收到","Received","もらった","받음")}</span><b>${formatMoney(income)}</b></div><div className="mp-wbar gold"><i style={{width:`${expense+income?income/(expense+income)*100:0}%`}}/></div></div><div className="mp-wcard"><div className="mp-wweeks">{weeks.map((w,i)=><div className="mp-wweek" key={i}><i style={{height:`${w/maxWeek*100}%`}}/><small>W{i+1}</small></div>)}</div></div><div className="mp-wnote">{monthTx.length?tr(`本月共 ${monthTx.length} 筆往來${biggest?`，最大一筆 $${formatMoney(biggest.amount)}`:""}。`,`There were ${monthTx.length} exchanges this month.`,`今月は ${monthTx.length} 件のやり取り。`,`이번 달 ${monthTx.length}건의 거래가 있었어요.`):tr("這個月還沒有金錢往來。","No transactions this month.","今月はまだやり取りがありません。","이번 달은 아직 거래가 없어요.")}</div></div>}</div></div>;
}
